# Generated by Django 4.1.5 on 2023-05-07 11:02

from django.db import migrations, models
import formula_one.utils.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('helpcentre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=63)),
                ('title', models.CharField(max_length=200)),
                ('query', models.TextField()),
                ('answer', models.TextField()),
                ('answer_file', models.FileField(blank=True, null=True, upload_to=formula_one.utils.upload_to.UploadTo('helpcentre', 'faq'))),
            ],
            options={
                'verbose_name_plural': 'faqs',
            },
        ),
        migrations.CreateModel(
            name='quickguide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_file', models.FileField(upload_to=formula_one.utils.upload_to.UploadTo('helpcentre', 'quickguide'))),
            ],
        ),
    ]
