# Generated by Django 4.1.5 on 2024-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcentre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='related_tag',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
