# Generated by Django 4.1.5 on 2024-06-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcentre', '0002_query_related_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='description',
            field=models.TextField(default='abcd'),
            preserve_default=False,
        ),
    ]
