# Generated by Django 4.1.5 on 2024-06-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpcentre', '0003_query_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='description',
        ),
    ]
