# Generated by Django 4.1.5 on 2024-06-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcentre', '0004_remove_query_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
